### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by SidFeng** [myronliu347/vue-carbon#11]
当有下拉选择时，控制台莫名其妙一直有这个报错，而且只要有点击事件，这个错误数字成倍叠加
![image](https://cloud.githubusercontent.com/assets/6702354/18504144/64c4d70e-7a93-11e6-89af-996dd31bcd30.png)

问题代码在这里

```
this.windowListener = (e) => {
      if (!this.$els.select.contains(e.target)) {
        this.hideSelect()
      }
    }
```

点击其他地方 this.$els.select 未null

**Comment by myronliu347** [comment]
请给出你使用这个组件的代码片段，便于模拟出错场景

**Comment by myronliu347** [comment]
已经在 0.4.2 版本中修复这个问题，多谢的你的支持!!!
