### ISSUE TITLE
看这个是基于某前端什么英文的网站,这个是可以免费使用吗?

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#12]
我在里面下载了个包,里面有个文档如下,英文,我英文不好,大概看了说是好像如果要用的话必须 provide credit. 这是什么意思呀?做项目可以免费用吗?另外觉得这个做的不错,有没有QQ交流群什么的?还有我刚学的VUE,这个可以实现热加载吗?应该怎么实现?

CARBON - Material Wireframe Kit

We may use this Kit as you want, in personal or commercial projects!
You may not redistribute it thought and if you include it in freebies links, collections etc. you must provide credit.

Finally, if you want, you may follow me on Dribbble and Twitter!

Enjoy!

**Comment by myronliu347** [comment]
总结了下你的问题， 解决如下：
1. CARBON 这个是设计资源，只是参考了它的配色
2. 至于热加载，使用vue-cli创建的项目是有这个功能的 
3. vue carbon 完全开源，可以随意使用，有问题给我提 issues , 我会及时解决
4. 目前 vue carbon 已经有使用文档： [Vue Carbon 使用文档](https://myronliu347.github.io/vue-carbon)
5. 最后至于QQ 群嘛，目前并不打算建，主要是怕人太少，有问题可以直接问我，我都会予以解答 （有时会晚点，工作原因）

**Comment by issmile** [comment]
我在电脑上跑起了里面的example.这个例子是热加载的?还是一下子载入所有组件的?

我放在微信里打开,第一次大概5-7秒加载时间,后来加载大概2-3秒.所以觉得好像是一次性加载了所有的?

看里面example的返回去的时候都是返回的初始状态,比如看完FORMS组件后按返回,home页面又变回了首屏,没有保存list当前的位置,看源码是设置了keep-alive,按官方介绍应该是是保存状态的呀,为什么没有保存当前滚动位置?如果要实现保存当前位置的话,应该怎么实现?

**Comment by myronliu347** [comment]
嗯，这个demo页面是没有做异步加载组件的, 这个官网有介绍 [动态载入组件](http://router.vuejs.org/zh-cn/lazy.html)   ,

 keep-alive 只是保存了组件状态，并没有保存滚动条的位置。

**Comment by myronliu347** [comment]
保存滚动条位置的实现：

首先给content 加上一个索引

``` html
<content v-ref:scroller></content>
```

切出是保存 scrollTop 切入是修改scrollTop

``` javascript
let scrollTop = 0

export default {
   //....
route: {
    activate (transition) {
      transition.next()
      Vue.nextTick(() => {
        this.$refs.scroller.$el.scrollTop = scrollTop
      })
    },
    deactivate (transition) {
      scrollTop = this.$refs.scroller.$el.scrollTop
      transition.next()
    }
  }
}

```
