### ISSUE TITLE
几个问题集合,1滚动条问题?2lazyload组件3自定义item4底部tabbar

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#13]
1.list可以显示滚动条吗?感觉应该要有个滚动条,如果电脑用户访问的话,有个滚动条会方便很多,最好能有个可选,是否显示
2.lazyload图片,这个功能很多UI框架都有,而且移动端需求很大,可不可以做一个这样的组件?或者如果自己想做的话应该怎么做?
3如何自定义item,比如无限加载LIST中,我想要做电商那种一行两个item这种,有没有什么建议规范?图片大小高度是怎么控制的,是否能用栅格自己随意搞item 还是一定要有一套规范?可不可以内置一个这样的
![image](https://cloud.githubusercontent.com/assets/20268011/18592862/72a40a78-7c6b-11e6-8a4c-15435ccceb6d.png)
这样的需求应该也很多的
4底部tabbar,已经有顶部tabbar了,再设置个底部tabbar 吧,不然就是重复造轮子了..如下图这样的
![image](https://cloud.githubusercontent.com/assets/20268011/18592643/7aee019e-7c6a-11e6-8d09-f436fa19dde7.png)
5,我提出issue,在一个里面跟帖好,还是新建issue好?

**Comment by myronliu347** [comment]
首先，多谢你的支持。
1. content 组件是带滚动条的，你也可以使用任何容器设置overflow:auto；
2. lazyload,  这个可以使用 [vue-lazyload](https://github.com/hilongjw/vue-lazyload)，大神写的，靠谱。
3. item 和 list 以及所有的css组件，你都可以自定义这个是不限制的，组件只是提供一个简单的方案
4. 底部的tabbar ,还有一些组件，我会在 国庆假期完成。
5. 新的问题还是新建一个issue，如果解决掉，就帮我关闭
