### ISSUE TITLE
目前准备基于vue-carbon编写app的一些问题？

### ISSUE THREAD

**Issue by peirancao** [myronliu347/vue-carbon#14]
1、请问如果我使用vue-carbon现在的版本 那么等 vue2 正式版发布了 迁移成本大么？
2、如果等待vue-carbon vue2的版本发布 时间会不会太久？

**Comment by myronliu347** [comment]
1. 迁移vue2的成本估计还是有点大，我现在已经在使用vue2开发了，里面还是有很多东西不一样，所以我会调整一些组件的参数和使用方式。
2. vue2的版本的时间可能会有点久，项目名称也会变化

**Comment by peirancao** [comment]
@myronliu347 谢谢 那么 现有版本还会继续维护吗？

**Comment by myronliu347** [comment]
会的，这个版本会一直维护

**Comment by 96NB** [comment]
表单的验证，这个库有什么好的形式么
text-field 封装了，类似vue-validator的库用不了了

**Comment by myronliu347** [comment]
多谢提醒， 我会尽快完善验证这一块的

**Comment by peirancao** [comment]
希望能尽早用上vue2.0版的啊。。

**Comment by myronliu347** [comment]
[muse-ui](https://github.com/museui/muse-ui) 早就在写了，国庆几天加个速，争取在十月底发出来
