### ISSUE TITLE
demo Picker 例子在 chrome android 上面无法滑动

### ISSUE THREAD

**Issue by phtwo** [myronliu347/vue-carbon#17]
rt
可能因为 chrome 本身有下滑的操作?

**Comment by myronliu347** [comment]
最近有点忙，这个问题，在国庆节期间修复吧

**Comment by myronliu347** [comment]
我在chrome浏览器试过，并没有这个问题啊， 请问，你的安卓版本是？

**Comment by phtwo** [comment]
5.1.1 LMY47V
MIUI 8.0
chrome 49.0.2623.105

**Comment by beeplin** [comment]
picker的确有问题，在我的好几个android设备上都是一滚动就抖动

**Comment by myronliu347** [comment]
fix in  [0.5.2](https://github.com/myronliu347/vue-carbon/releases/tag/0.5.2)
