### ISSUE TITLE
如何扩展组件?button 组件没有放置url属性,我需要扩展Url属性

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#18]
![image](https://cloud.githubusercontent.com/assets/20268011/18674503/09ba3c20-7f82-11e6-8340-cc394eb26279.png)

如图,想用mixins: VueCarbon.button,方法,然后替换template来实现模板改变
,却发现没有用,好像是VueCarbon.button 这个值为空,但是直接用button也没用.不知道应该怎么弄了.难道只有复制源码来定义?

**Comment by myronliu347** [comment]
使用这种方式绑定url

``` html
 <button :href="url" text="button"></button>
<script>
export default {
  data () {
    return {
        url: '/test'
    }
  }
}
</script>
```
