### ISSUE TITLE
vue2.0 support?

### ISSUE THREAD

**Issue by beeplin** [myronliu347/vue-carbon#22]
vue 2.0 has been officially released for 4 days~

**Comment by myronliu347** [comment]
[muse-ui](https://github.com/museui/muse-ui)  正在开发， 尽快。。。

**Comment by beeplin** [comment]
为啥放弃vue-carbon这个名字另开一个呢？我觉得vue-carbon这个名儿很好啊

**Comment by beeplin** [comment]
另外，vue-carbon是我试过的唯一在300块钱低端android机器上不太卡的material design实现。赞一个。

**Comment by myronliu347** [comment]
carbon 是之前那个设计图的名字，这一个我想支持更多的主题

**Comment by beeplin** [comment]
哦明白。新项目建议参照mint-ui，把swipe、lazyload、progress几个常用组件补上。另外，现在的carbon还有几个小问题：
1. nav和tab都没有横向切换动画，
2. itemlist上下滑动时，会错误触发ripple
3. picker在设备上响应不好，有抖动。
期待！

**Comment by myronliu347** [comment]
好的，多谢你的意见，我会更努力，把这个做的更好

**Comment by beeplin** [comment]
对了，将来的muse-ui的api会和carbon基本一样吗？一样的话，用户可以先用vue1写界面，将来方便升级到muse+vue2。

实际上vue1和2在组件开发上几乎没啥区别，最大的变化都在后台。只要不是刻意用到那几个过时的语法，尤其是别是用到大量的自定义directive，往往直接跑一下官方那个升级辅助程序，根据提示改几处地方就搞定了。

但是要是组件库的api变了，那改起来可就麻烦了。。。

**Comment by myronliu347** [comment]
muse-ui  大部分会借鉴 carbon 的 API， 但仍然有许多地方有较大的改变，主要有如下几点：
1. 双向绑定被删除了，之前 弹出层等一系列组件，不能再组件内部改变，这些地方需要加入事件控制
2. vue2的dom事件和 组件事件是分开，所以有些事件名称会做修改， 例如直接写 change， click 等等
3. carbon 之前有些地方不符合material design 的设计规范，参数的命名也不是很标准 例如 `button` 这个组件跟原来的组件重复了，这里会把它分割为 `flatButton` 和 `raisedButton`  
4. 有些组件的使用方式也会改变 例如 `list` `listItem`， `drawer` 这个系列的， 原来的使用方式有点别扭。

改动还挺多的，muse-ui 将是一个独立的项目， 更好的 material design 的实现

**Comment by beeplin** [comment]
嗯，支持。api的变化的确是不可避免的。话说考虑给组件标签名加前缀吗？

希望muse坚持使用目前的carbon配色作为默认主题。这个主题太赞了。

**Comment by myronliu347** [comment]
组件统一前缀 `mu-`

**Comment by kristianmandrup** [comment]
huh!?
