### ISSUE TITLE
日期选择组件里面的点击按钮没有做波纹效果

### ISSUE THREAD

**Issue by beeplin** [myronliu347/vue-carbon#23]
使用起来跟其他组件有点不匹配

**Comment by myronliu347** [comment]
这里不是按钮，所以并不需要波纹效果， 不过动画，我会稍作调整的

**Comment by beeplin** [comment]
我感觉你的设计逻辑是，只要可点击的地方都有波纹。不仅是按钮，比如可点击的itemlist里面的item也有波纹
