### ISSUE TITLE
[Vue warn]: Unknown custom element

### ISSUE THREAD

**Issue by jie** [myronliu347/vue-carbon#24]
import VueCarbon from 'vue-carbon'
Vue.use(VueCarbon)

还是会报错：
[Vue warn]: Unknown custom element: <scroll-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by myronliu347** [comment]
请问是你使用哪些组件报错了，还是初始化就有问题？

**Comment by myronliu347** [comment]
我先关掉了， vue-carbon 是针对vue 1.0 开发的， 如果引用在 vue2环境下是有这种问题， 请给出具体情况，我才好修复，多谢
