### ISSUE TITLE
npm install了，webpack报无法找到vue-carbon

### ISSUE THREAD

**Issue by chenchanLau** [myronliu347/vue-carbon#25]
var _vueCarbon = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"vue-carbon\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
安装的是0.5.0的版本，前端小白，求指点。谢谢。

**Comment by myronliu347** [comment]
实在抱歉，上次打包的时候，不知道怎么没有生成文件， 请重新安装，谢谢！
