### ISSUE TITLE
如何使用overlay 做一个引导页?

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#26]
比如这样的微信打开浏览器引导?

![image](https://cloud.githubusercontent.com/assets/20268011/19232647/7e31b538-8f13-11e6-8719-3cfa55047d92.png)

图片素材https://raw.githubusercontent.com/kujian/weixinTip/master/live_weixin.png
我应该怎么组合这个组件呢?如何把内容放在遮罩上?我看源码遮罩并没有插槽,其他应用遮罩的组件,也没看到怎么引用的这个组件...

**Comment by myronliu347** [comment]
本身这个组件库是没有提供引导页的，我说下我的思路吧：
1. 首先是 overlay组件， 需要在使用时重置一下它的zIndex ，这个写 style即可
2. 高亮需要引导的部分， 原理很简单 zIndex 比overlay 大一点即可
3. 引导上的文字和图片， 同样适用zIndex 比overlay值要大， 然后适用 position 控制位置

**Comment by issmile** [comment]
@myronliu347  重置 zindex  style 有什么讲究吗,仔细看你写的代码,有个对象专门用于设置zindex,一般这个遮罩我设置多少合适?

**Comment by myronliu347** [comment]
随意，给大点最好，保证在最上层

**Comment by issmile** [comment]
@myronliu347 好的谢谢
