### ISSUE TITLE
vue-carbon 最近会延缓更新进度

### ISSUE THREAD

**Issue by myronliu347** [myronliu347/vue-carbon#27]
首先，感谢大家一直以来的支持，最近正在全力开发 **vue-carbon** 针对 vue2 的升级版 [muse-ui](https://github.com/museui/muse-ui) ， 主要解决 *_vue-carbon *_ 的现有问题如下：
1. vue2 版本可以使用
2. 严格遵守 material design 的设计风格 （vue-carbon 现在有些地方并不符合标准）
3. 可以适配多种主题
4. api 的改善，是有方式更加简单方便
5. 不止于移动端，ie10以上的pc都可以使用

由于个人精力有限，在最近 1个多月内，**vue-carbon** 的更新进度会延缓，但是让然会第一时间完成bug修复， 大家可以放心提bug

**Comment by beeplin** [comment]
支持！期待Muse！

**Comment by myronliu347** [comment]
已发布 `alpha` 版 , [Muse UI](https://museui.github.io) 文档基本补全， 主题的会在一周内补全文档和使用。
