### ISSUE TITLE
出现一个莫名其妙的问题

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#29]
npm run dev 下是这样的
![image](https://cloud.githubusercontent.com/assets/20268011/19569799/9c755676-9729-11e6-8fa0-e4bde7eab574.png)
npm run build 后这样了,是什么鬼?
![image](https://cloud.githubusercontent.com/assets/20268011/19569804/a5094676-9729-11e6-84cb-70681a710c23.png)
我好长时间没跟新版本了,和版本有关系吗?我要怎么升级版本?

**Comment by myronliu347** [comment]
你更新到哪个版本了，给我看看

**Comment by issmile** [comment]
@myronliu347 怎么看跟新到哪个版本了？

**Comment by myronliu347** [comment]
vue的版本

**Comment by issmile** [comment]
现在还是版本1,不知道要怎么查VUE的版本,npm不太会...

**Comment by myronliu347** [comment]
有没有报错信息呢

**Comment by myronliu347** [comment]
如果没有报错，那有可能是你的浏览器不支持 `input[type=range]`

**Comment by issmile** [comment]
@myronliu347 感觉应该不是吧,Dev还支持的,浏览器都是同一个,不过我先升级下版本什么的看看.

**Comment by issmile** [comment]
我去,其他浏览器真的能看到,就搜狗不行....这要怎么办啊

**Comment by issmile** [comment]
为什么build不是用的那个标签吗?

**Comment by issmile** [comment]
我找到问题所在了,但是不知道怎么修复,搜狗浏览器会出现这样的input[type=range]::-webkit-slider-thumb:before,其他浏览器标签就只有input[type=range] 这要怎么解决

**Comment by issmile** [comment]
/\*   input[type="range"]::-webkit-slider-thumb:before {
  position: absolute;
  top: 50%;
  right: 100%;
  width: 2000px;
  height: 2px;
  margin-top: -1px;
  z-index: 1;
  background: @red;
  content: ' ';
} */我 在源码里把这个注释了就好了.....

**Comment by myronliu347** [comment]
应该是被盖住了，其它浏览器 这个伪元素是不会识别 :before 的

**Comment by myronliu347** [comment]
实在是不好意思，最近的精力全放在muse-ui 上了，没有帮你你处理问题，实在抱歉
