### ISSUE TITLE
我想做个滚动的组件,应该怎么弄?怎么配合你的框架做?

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#31]
类似这样的,VUE中突然不知道怎么下手了
![image](https://cloud.githubusercontent.com/assets/20268011/19723121/70eb9c22-9bac-11e6-9bbc-a68bd3d5718b.png)

**Comment by myronliu347** [comment]
vue-carbon 没有这个组件，你可以使用这个 [vue-swipe](https://github.com/ElemeFE/vue-swipe)
