### ISSUE TITLE
ripple功能

### ISSUE THREAD

**Issue by lucian-czh** [myronliu347/vue-carbon#32]
<a href="javascript:;" class="button" v-el:button>
  <ripple :trigger="$els.button"></ripple>
</a>

vue 2.0 没有了v-el的指令，那么该如何实现呢？

**Comment by myronliu347** [comment]
`ref`

**Comment by myronliu347** [comment]
[touchRipple](https://github.com/museui/muse-ui/blob/master/src/internal/touchRipple.vue)

**Comment by lucian-czh** [comment]
thanks

**Comment by lucian-czh** [comment]
有木有具体的实现呢？ 参考下。谢谢。

**Comment by myronliu347** [comment]
touchRipple  发的这个就是具体实现啊
