### ISSUE TITLE
Do not use built-in or reserved HTML elements as component id: button 

### ISSUE THREAD

**Issue by hellinnocence** [myronliu347/vue-carbon#34]
version 0.5.1

vue.js?3de6:2611 
[Vue warn]: Do not use built-in or reserved HTML elements as component id: button 

vue.js?3de6:2611
[Vue warn]: Do not use built-in or reserved HTML elements as component id: switch

**Comment by myronliu347** [comment]
vue 1.0是不会有这个问题的，是否使用的vue2.0呢？

**Comment by hellinnocence** [comment]
是用了2.0

**Comment by hellinnocence** [comment]
不能用2.0吗？

**Comment by myronliu347** [comment]
这个项目只支持到1.0

**Comment by hellinnocence** [comment]
用MuseUI也遇到这个错误

**Comment by myronliu347** [comment]
muse 没有这个问题，所有的组件都有 `mu-` 前缀
