### ISSUE TITLE
如何在每次进入home的时候显示bottomNav,在进入另一个路由的时候隐藏bottomNav?

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#36]
我是想用vue-router的钩子来实现,无奈不知道为什么没起作用....

 beforeRouteLeave (to, from, next) {
    console.log("beforeRouteLeave");
    from.setBottomNav(false);//隐藏bottomNav
  }

**Comment by myronliu347** [comment]
将bottomNav放在home页面就可以啦

**Comment by issmile** [comment]
汗,我居然没想到
