### ISSUE TITLE
适配vuejs 2.0版本

### ISSUE THREAD

**Issue by tankxxl** [myronliu347/vue-carbon#38]
比如：
有一些v-el:trigger指令在vuejs 2.0下出错。

**Comment by myronliu347** [comment]
vue-carbon 是基于vue1.0版本开发， 2.0有新的项目 [muse ui](https://museui.github.io)

**Comment by zyzypy** [comment]
Uncaught TypeError: Cannot read property 'trigger' of undefined
我刚学vue，以为语法哪错了，原来是基于vue1.0版本的，没注意到文档第一句的说明。。
