### ISSUE TITLE
关于 Cordova 打包问题

### ISSUE THREAD

**Issue by gongph** [myronliu347/vue-carbon#40]
最近想用 cordova 开发一个手机app， 技术路线是 webpack + vue(.vue单文件) + es6 。 然后想请教下 @myronliu347  , cordova 是否可以把单页面应用打包成 apk ?  @F-loat

**Comment by gongph** [comment]
由于我不是太懂，希望能请教下。希望您不吝赐教！

**Comment by myronliu347** [comment]
可以的，参见这里 [使用 Cordova 和 Vue.js 创建移动应用](http://gold.xitu.io/entry/57de419e0bd1d00057f2fe45/)

**Comment by gongph** [comment]
不是通过 `<script>` 这种在页面上引入，而是通过 npm 来进行模块管理的移动端项目。例如 `app.vue` 单文件组件 能行吗？

**Comment by myronliu347** [comment]
不太懂，只要使用了 `*.vue`或者es6最后肯定是要build的，另外html用`script` 也是必须的，

**Comment by gongph** [comment]
传统的 `*.vue` 单文件，如果不build的话，我们可以通过 `npm start` 启动项目，然后通过访问 `http://localhost:8080` 可以访问页面。我在想，用cordova是否也可以做到无须 build 再在页面中引入。

**Comment by myronliu347** [comment]
那个方式只是在起了一个node服务端返回js，css，html等文件，实际上还是build了的

**Comment by gongph** [comment]
@myronliu347  那咱这个组件ui，也是在 *.vue 中使用的啊，如果要封装成 .apk 怎么弄呢？

**Comment by myronliu347** [comment]
build之后会生成一个js文件，然后再html引入即可, [使用 Cordova 和 Vue.js 创建移动应用
](http://gold.xitu.io/entry/57ea26f5da2f600060e59c5e/) 这篇文章里有提到.vue组件的使用

**Comment by gongph** [comment]
谢谢 @myronliu347 指教。收下我的膝盖！
