### ISSUE TITLE
滚动条的兼容问题

### ISSUE THREAD

**Issue by liguanrui** [myronliu347/vue-carbon#43]
使用`scroll-view`，当`list > item-cell`的个数很多的时候（大概20个），Android滚动体验，效果非常差！会出现一片空白，然后再缓慢加载出来的样子。

```
<scroll-view v-ref:scroller>
  <list>
     <item-cell link v-link="menu.link" v-for="menu in group.children">
       <item-title>{{menu.title}}</item-title>
     </item-cell>
   </list>
</scroll-view>
```
网上查了一下据说是以下CSS3属性设置在Android上的表现不佳引起

> -webkit-overflow-scrolling: touch;

测试环境
- Android 6.0
- vue-carbon 0.5.2

**Comment by myronliu347** [comment]
对，一般情况下不要用div scroll, 用window就好，这个scroll-view可以不使用
