### ISSUE TITLE
可以直接导入dist里的js和css使用吗，改怎么用

### ISSUE THREAD

**Issue by jlcool** [myronliu347/vue-carbon#53]
可以直接导入dist里的js和css使用吗，改怎么用，现在项目没有用webpack，全部修改来不及了

**Comment by myronliu347** [comment]
<link rel="stylesheet" href="https://unpkg.com/muse-ui/dist/muse-ui.css">
<script src="https://unpkg.com/muse-ui/dist/muse-ui.js"></script>

Vue.use(MuseUI)
