### ISSUE TITLE
引用组件报错...区域大哥不要放弃呜呜呜呜, 好不容易找到个好看的ui

### ISSUE THREAD

**Issue by MerlinAhh** [myronliu347/vue-carbon#54]
o(╥﹏╥)o

**Comment by myronliu347** [comment]
这个项目是给予vue1.0版本实现，目前已经废弃，建议您使用[muse-ui](https://muse-ui.org/#/zh-CN)
然后安装 [carbon 主题](https://github.com/museui/muse-ui-carbon-theme)
