### ISSUE TITLE
在中低端Android机上卡顿严重

### ISSUE THREAD

**Issue by hstarorg** [myronliu347/vue-carbon#7]
高端机没有，暂未测试~

**Comment by myronliu347** [comment]
之前有试过4.4以上的机器效果还算正常，uc上会差很多，
请问你测试的是安卓哪个系统嗯，我去测试下

**Comment by hstarorg** [comment]
红米Note3全网通低配版（系统默认浏览器）

**Comment by myronliu347** [comment]
之前用红米2 android4.4.4 系统测试，动画都还可以，请问是部分组件卡顿，还是所有？

**Comment by hstarorg** [comment]
就是demo的首页上下滑动就会一卡一卡的。

**Comment by myronliu347** [comment]
有些浏览器在div scroll 上的支持不会很好，只要不使用 content 组件做布局就可以了

**Comment by hstarorg** [comment]
好的，感谢解惑~
