### ISSUE TITLE
表单提交

### ISSUE THREAD

**Issue by kenzone** [myronliu347/vue-carbon#8]
用了button组件,但不支持表单的type="submit",无法做默认的表单提交

**Comment by myronliu347** [comment]
button 组件使用的是 a 标签，不会有表单提交的操作的

**Comment by kenzone** [comment]
原本使用的是默认的提交按钮 <input type="submit" value="提交">
想改用<button>组件, 但是就少了默认提交的功能, 想问下怎么处理?

**Comment by myronliu347** [comment]
监听 click 事件， 在里面调用 form 的 submit方法 手动提交

**Comment by kenzone** [comment]
目前是这样处理的, 只是不是很方便, 希望后续能增加这个支持, 感谢
另外表扬一下这个库很赞!

**Comment by myronliu347** [comment]
好的，多谢！
