### ISSUE TITLE
样式,标签冲突

### ISSUE THREAD

**Issue by kenzone** [myronliu347/vue-carbon#9]
提个建议
1.样式的class最好加个前缀, 例如cb-modal, cb-button, 目前的写法与原本的项目样式冲突了,导致需要全局修改
2.组件名不要使用HTML原生标签, 例如button, content等, 原因同上

**Comment by myronliu347** [comment]
嗯嗯，多谢,这个确实是个大问题

**Comment by myronliu347** [comment]
样式冲突的问题已经解决好了，组件名称现在不好随意更改，涉及到的页面和文档太多，怕修改不全
